feat: make sure the bot mutes it's own microphone before joining
meetingbot/meetingbot pull request #17
Opened 2024-11-05 15:26 UTC by sarahsimionescu

2024-11-05 15:26 UTC, sarahsimionescu commented
* **#19** <a href="https://app.graphite.dev/github/pr/meetingbot/meetingbot/19?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#18** <a href="https://app.graphite.dev/github/pr/meetingbot/meetingbot/18?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>
* **#17** <a href="https://app.graphite.dev/github/pr/meetingbot/meetingbot/17?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @sarahsimionescu and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-11-05 16:05 UTC, err53 requested changes

2024-11-05 16:05 UTC, err53 commented on src/bots/teams/src/index.ts
> +  await page.locator(`[data-tid="toggle-mute"]`).click();
Can we have some kind of check to make sure that it only toggles mute if it's currently unmuted? E.g. if Teams changes it's default behaviour down the line for some reason.

2024-11-08 22:33 UTC, sahibkhokhar commented on src/bots/teams/src/index.ts
> +  await page.locator(`[data-tid="toggle-mute"]`).click();
Should be done with all of the bots

2024-11-19 14:20 UTC, sahibkhokhar approved these changes

2024-11-20 14:59 UTC, sarahsimionescu commented
### Merge activity

* **Nov 20, 9:59 AM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/meetingbot/meetingbot/17).

2024-11-20 14:59 UTC, merged